force-app/main/default/objects/Limit__c/Limit__c.object-meta.xml
<CustomObject>
    <description>Used to store details about each limit that should be tracked</description>
    <label>Limit</label>
    <nameField>
        <label>Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <inlineHelpText>If there are any errors while retrieving the limit, they will be recorded here.</inlineHelpText>
    <label>Errors</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/LimitKey__c.field-meta.xml
<CustomField>
    <fullName>LimitKey__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The API name of the limit that corresponds to the map in the OrgLimits class</inlineHelpText>
    <label>Limit Key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Limit__c/fields/NextRetrieveTime__c.field-meta.xml
<CustomField>
    <fullName>NextRetrieveTime__c</fullName>
    <formula>LastRetrieveTime__c + (RetrieveIntervalHours__c/24)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The next time the limit will be retrieved</inlineHelpText>
    <label>Next Retrieve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LimitSnapshot__c/LimitSnapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshots of each limit</description>
    <label>Limit Snapshot</label>
    <nameField>
        <displayFormat>LS-{0000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LimitSnapshot__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <referenceTo>Limit__c</referenceTo>
    <relationshipLabel>Limit Snapshots</relationshipLabel>
    <relationshipName>Limit_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LimitSnapshot__c/fields/MaximumValue__c.field-meta.xml
<CustomField>
    <fullName>MaximumValue__c</fullName>
    <inlineHelpText>The maximum value for the org at the time of the snapshot</inlineHelpText>
    <label>Maximum Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitSnapshot__c/fields/PastRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>PastRetentionPeriod__c</fullName>
    <formula>CreatedDate &lt;  (NOW() -  Limit__r.SnapshotRetentionDays__c)</formula>
    <label>Past Retention Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LimitSnapshot__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>The current value of the limit at the time of the snapshot</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LimitsUtil.cls
public with sharing class LimitsUtil {
    public static void retrieveLimits() {
        // get the current org limits
        Map<String,System.OrgLimit> limitsMap = OrgLimits.getMap();

        List<LimitSnapshot__c> snapshots = new List<LimitSnapshot__c>();
        List<Limit__c> limitsToUpdate = new List<Limit__c>();
        
        // Query the limits to track and loop through them to record them
        for (Limit__c lim : [SELECT Id, LimitKey__c FROM Limit__c WHERE NextRetrieveTime__c = null OR NextRetrieveTime__c < :System.now() ]) {
            if (!limitsMap.containsKey(lim.LimitKey__c)) {
                lim.Errors__c = INVALID_LIMIT;
                limitsToUpdate.add(lim);
            } else {
                System.OrgLimit orgLimit = limitsMap.get(lim.LimitKey__c);
                snapshots.add(new LimitSnapshot__c(
                    Limit__c = lim.Id,
                    MaximumValue__c = orgLimit.getLimit(),
                    Value__c = orgLimit.getValue()
                ));
            }
        }

        insert snapshots;
        update limitsToUpdate;
    }

    public static void deleteLimits() {
        // Delete all snapshots older than the retention days set on each limit
        Database.delete([SELECT Id FROM LimitSnapshot__c WHERE PastRetentionPeriod__c = true]);
    }

    private static final String INVALID_LIMIT = 'The limit key is invalid. Please check the key and update.'; 

}