force-app/main/default/objects/Limit__c/Limit__c.object-meta.xml
<CustomObject>
    <description>Used to store details about each limit that should be tracked</description>
    <label>Limit</label>
    <nameField>
        <label>Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit__c/fields/AlertThreshold__c.field-meta.xml
<CustomField>
    <fullName>AlertThreshold__c</fullName>
    <inlineHelpText>If the limit exceeds the threshold, then trigger alerts</inlineHelpText>
    <label>Alert Threshold</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/ChangeThreshold__c.field-meta.xml
<CustomField>
    <fullName>ChangeThreshold__c</fullName>
    <defaultValue>0.2</defaultValue>
    <inlineHelpText>The threshold for the amount of change from one measurement to the other that should trigger alerts.</inlineHelpText>
    <label>Change Threshold</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <inlineHelpText>If there are any errors while retrieving the limit, they will be recorded here.</inlineHelpText>
    <label>Errors</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/LimitKey__c.field-meta.xml
<CustomField>
    <fullName>LimitKey__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The API name of the limit that corresponds to the map in the OrgLimits class</inlineHelpText>
    <label>Limit Key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Limit__c/fields/SnapshotRetentionDays__c.field-meta.xml
<CustomField>
    <fullName>SnapshotRetentionDays__c</fullName>
    <defaultValue>365</defaultValue>
    <inlineHelpText>The number of days to retain snapshots. Any snapshots older will be deleted. Leave blank to retain all snapshots</inlineHelpText>
    <label>Snapshot Retention (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitSnapshot__c/LimitSnapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshots of each limit</description>
    <label>Limit Snapshot</label>
    <nameField>
        <displayFormat>LS-{0000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LimitSnapshot__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <referenceTo>Limit__c</referenceTo>
    <relationshipLabel>Limit Snapshots</relationshipLabel>
    <relationshipName>Limit_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LimitsUtilTest.cls
@isTest
public with sharing class LimitsUtilTest {
  @isTest
  static void testRetrieveLimits() {
    Limit__c testLimit = (Limit__c) TestFactory.createSObject(
      new Limit__c(
        Name = 'API',
        LimitKey__c = 'DailyApiRequests',
        AlertThreshold__c = .8,
        ChangeThreshold__c = .2
      ),
      true
    );

    Test.startTest();
    LimitsUtil.retrieveLimits();
    Test.stopTest();

    List<LimitSnapshot__c> snapshots = [
      SELECT Id
      FROM LimitSnapshot__c
      WHERE Limit__c = :testLimit.Id
    ];
    System.assert(
      !snapshots.isEmpty(),
      'A limits snapshot should have been recorded'
    );
  }

  @isTest
  static void testRetrieveLimitsError() {
    Limit__c testLimit = (Limit__c) TestFactory.createSObject(
      new Limit__c(
        Name = 'API',
        LimitKey__c = 'BadLimitName',
        AlertThreshold__c = .8,
        ChangeThreshold__c = .2
      ),
      true
    );

    Test.startTest();
    LimitsUtil.retrieveLimits();
    Test.stopTest();

    testLimit = [
      SELECT Id, Errors__c, (SELECT Id FROM Limit_Snapshots__r)
      FROM Limit__c
      WHERE Id = :testLimit.Id
      LIMIT 1
    ];
    System.assert(
      testLimit.Limit_Snapshots__r.isEmpty(),
      'No limits snapshots should have been recorded'
    );
    System.assert(
      testLimit.Errors__c != null,
      'An error should have been added to the limit record'
    );
  }

  @isTest
  static void testDeleteLimits() {
    Limit__c testLimit = (Limit__c) TestFactory.createSObject(
      new Limit__c(
        Name = 'API',
        LimitKey__c = 'DailyApiRequests',
        AlertThreshold__c = .8,
        ChangeThreshold__c = .2,
        SnapshotRetentionDays__c = 0
      ),
      true
    );

    LimitsUtil.retrieveLimits();

    Test.startTest();
    LimitsUtil.deleteLimits();
    Test.stopTest();

    List<LimitSnapshot__c> snapshots = [
      SELECT Id
      FROM LimitSnapshot__c
      WHERE Limit__c = :testLimit.Id
    ];
    System.assert(
      snapshots.isEmpty(),
      'All limits snapshots should have been deleted'
    );
  }
}